name: Amens Tech
type: cybersecurity_software_factory
country: Belgium

head_office:
  city: Zaventem
  country: Belgium
  timezone: Europe/Brussels

working_languages:
  - French
  - English

development_language: Python

slack:
  workspace: amens-tech
  default_channel: amens-dev

github:
  organization: Amens-Tech
  os_repository: amens-os
